describe('Покупка товаров на сайте https://testqastudio.me/', () => {
  it('Добавление товаров в корзину и оформление покупки', () => {
    cy.visit('https://test.qa.studio/')
    cy.contains('БРОММС Двухместная кровать').click()
    cy.get('.summary > .cart > .product-button-wrapper > .quantity > .increase').dblclick()
    cy.contains('В корзину').click()
    cy.get('#cart-modal > .off-modal-layer').click()
    cy.get('#menu-top > .menu-item-home > a').click()
    cy.contains('КЛЛАРИОН Низкий столик').click()
    cy.contains('В корзину').click()
    cy.get('.woocommerce-mini-cart__buttons > [href="https://test.qa.studio/cart/"]').click()
    cy.get('.checkout-button').click()
    cy.get('#billing_first_name').type('Иван')
    cy.get('#billing_last_name').type('Иванов')
    cy.get('#billing_address_1').type('ул. Тестовая, д. 1')
    cy.get('#billing_city').type('Москва')
    cy.get('#billing_state').type('Юг')
    cy.get('#billing_postcode').type('123456')
    cy.get('#billing_phone').type('+79011234567')
    cy.get('#billing_email').type('test@test.com')
    cy.get('#place_order').click()
    cy.contains('Ваш заказ принят. Благодарим вас.').should('be.visible')
  })
})